// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFV4ywT7RazK71JL1TyytqAgO1aEJU3GQ',
    appId: '1:442330947281:web:6a36d9bb1089d4a5486ff0',
    messagingSenderId: '442330947281',
    projectId: 'flutter-chat-app-e3756',
    authDomain: 'flutter-chat-app-e3756.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e3756.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyGdwOnNkQr-q7c6s5nq8UNPZZAM-JeBg',
    appId: '1:442330947281:android:9a144f00a8835ed1486ff0',
    messagingSenderId: '442330947281',
    projectId: 'flutter-chat-app-e3756',
    storageBucket: 'flutter-chat-app-e3756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgW_ahUCkEiYLhh19NXVvxP_L6Kg7_vdQ',
    appId: '1:442330947281:ios:6cc78a906d526756486ff0',
    messagingSenderId: '442330947281',
    projectId: 'flutter-chat-app-e3756',
    storageBucket: 'flutter-chat-app-e3756.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}